# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 소개
    url: /
    weight: 10
  - name: 연구분야
    url: /#research
    weight: 11
  - name: 논문
    url: /#publications
    weight: 12
  - name: 구성원
    url: /#members
    weight: 13
  - name: 갤러리
    url: /#gallery
    weight: 14
  - name: 프로젝트
    url: projects/
    weight: 20
  - name: 강의
    url: courses/
    weight: 30
  - name: 문의
    url: /#contact
    weight: 40
